### ISSUE TITLE
transgui-5.8-setup无法安装

### ISSUE THREAD

**Issue by LYCX2015** [leonsoft-kras/transmisson-remote-gui#972] opened 2017-07-07 00:57 UTC
win10平台，64位系统，5.8版本无法安装，提示文件已损坏，试过不同的下载器下载，试过下载过多次，都会提示损坏，5.7版本下载后正常使用

**Comment by Arcanemagus** [comment] 2017-07-07 01:16
Or in English:

The v5.8.0 installer seems to be corrupted.
```
The setup files are corrupted. Please obtain a new copy of the program.
```
![image](https://user-images.githubusercontent.com/427137/27939072-35769a2e-6277-11e7-9ede-acdc8c45b932.png)

**Comment by Gaudi111** [comment] 2017-07-07 02:50
I can confirm I am getting the same issue.
Hashes for downloaded file:
CRC32: D2CE31FF
MD5: 1EEC765CF4EE08C44559595453A2DA7E
SHA-1: 5ECF1DF0349B7D94F45E963304D94F2813C16BFE

**Comment by PeterDaveHello** [comment] 2017-07-07 10:01
Can you please try again? Should be made by accident.

**Comment by Tharn** [comment] 2017-07-07 15:19
Just downloaded the executable, it works now.

**Comment by PeterDaveHello** [comment] 2017-07-07 17:31
I think we can close it now.

**Closed by PeterDaveHello** 2017-07-07 17:31 UTC

**Comment by leonsoft-kras** [comment] 2017-07-07 23:24
Peter, this is you replaced the version for Windows?

**Comment by Arcanemagus** [comment] 2017-07-07 23:39
@leonsoft-kras Correct, new hashes:

```
CRC32: F48E44E2
MD5: 0EE33652E0B128EE40DE979C23D77426
SHA-1: B7B737EF637E3F13FF12EBAE41FA55E1D5ED4228
SHA-512: 85B0B6B46C267A66B7DE955B95D126A12612AD6BE8A73B4371C7F2AC0D1EE5C1026EAF68BC41EB04FF39956E7E92592FA8BDD89A79BC75EE5FFB22E8637BD3AD
```

**Comment by PeterDaveHello** [comment] 2017-07-08 06:58
I'll try to make Windows build automatic on Travis CI in future, still working on Raspberry Pi release and MacOS TLS issue.

**Comment by leonsoft-kras** [comment] 2017-07-08 08:14
I did not understand why the version for Windows is slightly different from the version on my computer. I'm trying to find out. Nothing serious. The program files are not changed.

I can compile a version for raspberry and windows. Everything is set up.

**Comment by PeterDaveHello** [comment] 2017-07-08 12:25
@leonsoft-kras not sure it's made by me by accident. Building on Travis can saving time and don't need to have a Windows and Raspberry Pi platform :)

**Comment by leonsoft-kras** [comment] 2017-07-08 12:29
Extensive experience programming suggests that the platform can accurately check the functioning of the program. Of course, I'm aware that you can make a program for another platform. ))
