### ISSUE TITLE
Download path is not absolute error ?

### ISSUE THREAD

**Issue by rd1** [leonsoft-kras/transmisson-remote-gui#891] opened 2016-03-17 01:27 UTC
not sure why but this happened:

right after adding a new connection, then adding a new torrent to download.

![downloadpathnotabsolute](https://cloud.githubusercontent.com/assets/1567489/13833624/e9ee6158-ebbd-11e5-8ea2-3100f442b4ef.png)

TRG 5.1.0

**Comment by leonsoft-kras** [comment] 2016-03-17 03:39
You are not set or not set up correctly matching directories.
In the settings T-R GUI there is even an example.

**Comment by rd1** [comment] 2016-03-18 03:28
i went through the add new connection wizard as i usually do.


the section [AddTorrentconnection_name] with the folders
was missing in the transgui.ini i copied it from the 1st connection's section and fixed the issue.


i made this github entry in order to see if others had this problem,
but clearly you don't want ppl to report problems or ideas. why even bother to try to help you make this program the best it can be?

**Comment by leonsoft-kras** [comment] 2016-03-18 04:32
Write the next time step by step, what you have done.
"It does not work" - that is not enough. There are no mediums.

**Comment by rd1** [comment] 2016-03-18 04:56
i think i might have an idea why this error.

i'm testing Qtransmission v2.92 while i still have old transmission 2.84 turned off.

the rpc path might be the culprit:/transmission/rpc

**Comment by iZeus83** [comment] 2016-03-20 14:44
Hello,

I have the same problem, so the paths are set correctly but I don't know how to fix. 

> i made this github entry in order to see if others had this problem,
but clearly you don't want ppl to report problems or ideas. why even bother to try to help you make this program the best it can be?

I need to make a github to download the file fixed?, thanks.

**Comment by zerg518** [comment] 2016-03-20 15:58
Maybe this is related to the same problem as here:https://github.com/SickRage/sickrage-issues/issues/1071
"I got into contact with the Transmission developers on IRC and they told me that Transmission validates the path if the "path" key is send in the RPC request, and this must be an absolute path since 2.90. However, if you omit the "path" key from the request Transmission will just use the default download directory."

**Comment by iZeus83** [comment] 2016-03-20 16:02
Hi zerg518

So the RPC path was changed?. I mean you should now to point to another path than: /transmission/rpc  ???

**Comment by zerg518** [comment] 2016-03-20 16:51
I mean RPC request to the Transmission (https://trac.transmissionbt.com/browser/trunk/extras/rpc-spec.txt)
3.4.  Adding a Torrent 
   Method name: "torrent-add" 
   Request arguments: 
   key                  | value type & description 
365
   "download-dir"       | string      path to download the torrent to

**Comment by zerg518** [comment] 2016-03-20 17:12
Another observation: when I add new torrent file using TRG for existing torrent (new trackers for example) - all works as expected. "existing torrent" - I mean torrent already added using WebUI
Problem with "Download path is not absolute " appears just after updating Transmission from 2.84 to 2.92

**Comment by zerg518** [comment] 2016-03-20 17:22
I've got it! ;-)   After setting remote to  local path mapping in in Tools->Application options->Path and then testing this setting (right click-open containing folder) the error message is gone.
But with Transmission 2.84 I never need tis setting to be set.

**Comment by iZeus83** [comment] 2016-03-20 19:10
> I've got it! ;-) After setting remote to local path mapping in in Tools->Application options->Path and then testing this setting (right click-open containing folder) the error message is gone.
But with Transmission 2.84 I never need this setting to be set.

Hello, please can you post what are you paths?, I'm still with no luck.

**Comment by zerg518** [comment] 2016-03-20 19:45
I am using Transmission plugin for the FreeNAS.  Storage drive is mounted to /media/ so default downloading path in Tools->"Transmission options" is "/media/downloads"
In Tools->"Application options"->Path I have set "/media/downloads=N:\downloads"
where N:\downloads is a shared folder on network drive

**Comment by iZeus83** [comment] 2016-03-20 19:55
> I am using Transmission plugin for the FreeNAS. Storage drive is mounted to /media/ so default downloading path in Tools->"Transmission options" is "/media/downloads"
In Tools->"Application options"->Path I have set "/media/downloads=N:\downloads"
where N:\downloads is a shared folder on network drive

Ok, I see that you have a similar mapping like me, I'm using DOCKER. the default location to downloads is:

/downloads that points to /mnt/user (that is what am I using in docker and it is the real path on the server), so in transmission I set: "/downloads=\\unhp\" and this config also works with the latest version of transmission and the official Remote Client GUI.

**Comment by zerg518** [comment] 2016-03-20 20:15
Strange. I have removed mapping (delete the string). I have no error. Close and open TRG - it works. So I do not know what happens but my last action was: add mapping and then test it by right button click on arbitrary torrent.

**Comment by iZeus83** [comment] 2016-03-20 22:00
Ok zerg518, I followed your steps and still no luck. Only the official remote gui was working for m, really strange :/

**Comment by Underground78** [comment] 2016-03-20 22:04
Related changes in Transmission code: https://trac.transmissionbt.com/changeset/14594.

**Comment by iZeus83** [comment] 2016-03-20 22:13
> Related change in Transmission code: https://trac.transmissionbt.com/changeset/14594. It probably requires some minor adjustments on the RPC call.

Hello, yep it seems this need some adjustments like the offical remote gui.

**Comment by rd1** [comment] 2016-03-21 03:56
Awesome find youguys ! Thanks

i hope Leonsoft (aka Alexander) here is listening. 

Alex, we're a community here and we're only trying to figure out how to make this software better ok ? We're not trying to bother you with "dumb ideas and bug reports". 

Things change as things progress, i hope you're listening and will keep TRG on top of those changes too.

Cheers

**Comment by leonsoft-kras** [comment] 2016-04-01 15:04
If I understand correctly, the problem in the transmission, instead of TRG?

**Comment by iZeus83** [comment] 2016-04-01 15:08
Hello, 

> If I understand correctly, the problem in the transmission, instead of TRG?

On TRG official, I hadn't this problem. Only ocurrs with TRG v5.1 or 5.2.

**Comment by leonsoft-kras** [comment] 2016-04-01 15:24
I introduced the latest sources of the synapse library and delete json library, so you can compile the latest versions of Lazarus.

Something went wrong. :(

**Comment by Underground78** [comment] 2016-04-01 15:59
I think the problem is just that Transmission changed something in the API or became more strict about that "path" parameter.

**Comment by iZeus83** [comment] 2016-04-01 16:03
> I introduced the latest sources of the synapse library and delete json library, so you can compile the latest versions of Lazarus.
> 
> Something went wrong. :(

Strange that !

I compiled with "Lazarus v1.4.4" ,all of this ok and I made the installer program fine. I cloned with git within this path: "https://github.com/leonsoft-kras/transmisson-remote-gui.git" .

But finally I get the error again :( . Strange because the download directory points to "/downloads" in options of transmission, so I'm using a docker system and then "/download" path is pointing to the real path that is "/download/personal" then you can see that path is NOT relative. Maybe I miss something.

**Comment by rd1** [comment] 2016-04-07 01:11
i installed transmissionbt for windows on a 2nd machine (https://sourceforge.net/projects/trqtw/)

 and used TRG windows to access it just like on linux, but the absolute path error pops-up when i want to add a new torrent.

i tried :
/=e:\
\\192.168.x.y=e:\
/d=e:\

all no go. however, the download path, incomplete and watch folders are properly written in settings.json

whats the right way to enter those paths ?

**Comment by iZeus83** [comment] 2016-04-07 21:19
Still have the problem, I'm using the official TRG because this work for me!

**Comment by rd1** [comment] 2016-04-07 22:04
i fixed it some how *scratches head* lol

all i did after adding a torrent was use "set location" on an already downloaded torrent, saved it in same folder.

maybe its the same issue as in my O.P. at top of this thread but this time it was with transmissionbt for windows not my nas..

**Comment by iZeus83** [comment] 2016-04-13 08:38
> i fixed it some how scratches head lol

all i did after adding a torrent was use "set location" on an already downloaded torrent, saved it in same folder.

maybe its the same issue as in my O.P. at top of this thread but this time it was with transmissionbt for windows not my nas..

Yes, me too... it works only when you have added a torrent before in the list and not when you have a clean install of TRG. :/

**Comment by rd1** [comment] 2016-04-13 19:03
idk, sometimes it works, other times you have to delete the torrent and add it again.

i think i'm gonna uncheck the box that says trash original torrent and just find a safe place to store all the torrents. ugh one more thing to clean up in computers.

This bug is freaking annoying. it seems to happen a lot on shutting down transmission too (win and linux in my case).

See, what's silly is, somebody somewhere knows of the bug and is giving a pseudo solution in the form of a message saying to use "set location blablabla" but **the source of the bug isn't fixed**.

it's gotta be something like corruption of the .resume file (or some database idk about?) transmission uses is the culprit. i mean maybe a bad commit of the information when adding torrents, something bypassing the OS or some misplaced bit of info, or too many things to juggle for transmission, idk. 

Barring any hardware failures (bad sectors, etc), there shouldn't be this kind of error.

Meanwhile we have to head on over to https://forum.transmissionbt.com/ and talk about this bug. 

There has to be something someone knows that can fix this bug.

**Comment by rd1** [comment] 2016-04-13 20:00
ok back to original topic, Absolute path error is still happening in v5.3 . 

i just tried adding a torrent and got the popup like in my OP.

the path hasn't changed on my nas
the transmision settings.json file hasn't changed either.

i deleted transgui.ini and reinstalled v5.3 fresh, no go.

Something's buggy in this version about paths.

**Comment by moonman** [comment] 2016-04-13 23:01
Someone is not understanding paths correctly.
For me everything works, be it on windows or linux.
On winsows absolute path starts with drive letter C:\\ on linux or mac it starts with root which is a forward slash /. 
For example my download folder on the NAS is /media/Files which is shared over samba as Torrents So the mapping should be 
/media/Files=\\192.168..x.x\Torrents
If you attached a remote drive in Windows it would look lime this /media/Files=X:\\

**Comment by iZeus83** [comment] 2016-04-13 23:22
I have the same situation as rd1, I set the paths correctly. I'm using a remote path like "/downloads" so this points to "/media/downloads" on my linux server because I'm using a docker system. TRG official works for me perfect, no problem for me when I'm adding a torrent. However, the situation is diferent when I'm using a fresh install of TRG v5.3 or older because "the  absolute path error" ocurs and you couldn't set any path.

**Comment by rd1** [comment] 2016-04-14 01:10
what can i say Moonman, it is what it is. i've only been using transmission and TRG for close to hum... 
4 years now... i may have somethings to learn but i doubt it is how to setup transmission on the server side the way i've been doing it for years.

There is something missing in v5.3 when creating a new connection, then adding a new torrent and i get this download dir not absolute error, not that it means anything i mean the default folder from settings.json should be used and is absolute obviously but TRG isn't reading it for some reason.

That's not on me, that's the code.

-that and the SSL/TLS not compiled for updates verification (other thread of mine)
-the whole context menu not showing the cut,copy paste when editing a torrent's name (other thread of mine) 
-the set location box not showing all previously entered paths but just a big fat browse button like this : 

![noprevpaths](https://cloud.githubusercontent.com/assets/1567489/14513872/6ba7d01a-01b9-11e6-952d-4ac08e71e22b.PNG)

i'm not sure but the code merging probably did a number behind the scenes

i'm hoping Leon can fix these bugs in the next update.

**Comment by batagy** [comment] 2016-04-15 23:07
Hi All!
I've yesterday found this new version (fork of official?), installed 5.3.0.
Me too, having this annoying bug. When adding new torrent, getting the "download directory path is no absolute". 

After reading whole of this thread, and messed with various attempts, I think I came to some conclusions.

**My environment:**
Transmission 2.92 runs on a Synology NAS in remote. Default download folder is:
_/volume1/Transmission/Zene_
This is set in TRG -> Tools -> Transmission Options -> Download -> Default download folder on remote host

Locally Windows 8.1 is used, and NAS is mounted locally on Z:\, so that I have download folder locally here:
_Z:\Zene_

**Conclusion 1:**
About path mapping in this menu:
TRG -> Tools -> Application options -> Paths
After messing with path mapping, I came to conclusion that this version of TRG has mapping order  reversed compared to the official 5.0.1 version. Because in old version I had this setting, worked correctly:
_Zene=/volume1/Transmission/Zene_

But in this TRG, the remote path should come first, and local path should be also absolute, so this is correct:
_/volume1/Transmission/Zene=Z:\Zene_

The correct mapping is needed, however it's nothing to do with the error in subject, that is caused by the below issue.

**Conclusion 2:**
The problem is how TRG handles the transgui.ini file. The ini file is located here:
_C:\Users\<user>\AppData\Local\Transmission Remote GUI\transgui.ini_

The problem is that the "[AddTorrent.address] section is missing in INI from a clean installation.
And if that section is not exising in INI, then TRG cannot handle it when adding a torrent.
This section of the ini is added to ini file first time, only when you change the "Set data location..." on an existing torrent. After that section created, issue goes away, and adding torrent working.

**How to check:**
Have a clean system, i.e. no TRG installed.
Install TRG, and set folder mapping.
Copy INI file from here to somewhere else:
_C:\Users\<user>\AppData\Local\Transmission Remote GUI\transgui.ini_
In this state, you cannot add torrents due to the error.
Follow below workaround.
Then new section to ini is added, compare this new ini to the previously copied ini file.
Try addin torrents, it will work.

**Workaround:**
in TRG, go to any existing old torrent,  select one.
Right click -> Set data location...
The existing location is pre-filled, you don't even need to change it, just press "OK" with same folder. Or change the folder with the "Browse" button locally. For this you need the path mapping correctly.

As soon as you first changed the data location, a new section is appearing in INI file:
In my case, after added 2 kind of different labelling folders this section added:

```
[AddTorrent.192.168.0.245]
FolderCount=2
Folder0=/volume1/Transmission/Miko
FolHit0=12
FolExt0=
LastDt0=2016.04.15.
Folder1=/volume1/Transmission/Zene
FolHit1=2
FolExt1=
LastDt1=2016.04.15.
LastMoveDir=/volume1/Transmission/Zene
PeerLimit=50
LastDownloadDir=/volume1/Transmission/Miko
Folder2=
FolHit2=-1
FolExt2=
LastDt2=

[AddTorrent]
Width=560
Height=526

```

So it does have 2 last used directory there saved in ini.
After this, adding torrents works properly!

**Solution needed:**
TRG doesn't handle the lack of [AddTorrent] section when adding to torrent.
I'm not a programmer, but some ways I guess:
1) One way, I think, TRG should add this section to ini when someone makes changes in folder mapping (TRG -> Tools -> Application options -> Paths ) , or if making any changes in Settings.
2) Or have this section added by default when creating the ini.
3) Or, when adding a torrent, and if this section is missing, add this section and don't put an error message.

Hopefully  this helps with this wonderful app future.

**Comment by rd1** [comment] 2016-04-15 23:21
hi batagy thanks for adding your experience here

Conclusion 2 is spot on, the ini file is missing settings when adding a new connection, as reported at the top of this thread.

**Comment by leonsoft-kras** [comment] 2016-04-16 03:43
batagy, bravo!
Excellent description!

**Comment by batagy** [comment] 2016-04-16 09:38
@leonsoft-kras 
Could you then please correct it?

**Comment by leonsoft-kras** [comment] 2016-04-16 10:26
I will try.
if I myself faced with these problems, it would be easier. I have to reproduce your problem, to find the error.

**Comment by batagy** [comment] 2016-04-16 17:24
Hi Leon,

OK, many thanks in advance.
Actually I clearly wrote down how to reproduce in my "How to check section". You only need to delete your INI file (stop TRG before, and backup INI somewhere of course), then set basic settings. Then try to add a torrent, That's all to reproduce.

**Comment by leonsoft-kras** [comment] 2016-04-17 13:24
Fixed in 5.3.1 and above.
The most likely cause of the problem is the transition to a new version of Lazarus.
Thanks Batagy.

**Closed by leonsoft-kras** 2016-04-17 13:24 UTC

**Comment by rd1** [comment] 2016-04-17 19:06
you're welcome.

**Comment by keizie** [comment] 2019-01-20 13:37
For the record, I met this bug with transgui 5.15.4 and 5.16.0, with magnet auto add option.
Came to this issue as history.txt read, and found "LastDownloadDir=@" in transgui.ini file.
(I don't know why such value. I usually add via watchdir feature)

After setting absolute path on right side, no more error dialog.

**Comment by gavin2n** [comment] 2019-09-14 13:55
Had this problem too when using UNC paths for folders in 5.17.0

Workaround for was to close the remote client, remove the [AddTorrent.. section from the config and relaunch. Adding then worked again.
