### ISSUE TITLE
Transmission Remote GUI doesn't work on MAC OS High Sierra 10.13

### ISSUE THREAD

**Issue by patrik-b** [leonsoft-kras/transmisson-remote-gui#1012] opened 2017-10-03 09:42 UTC
Using High Sierra 10.13 (17A365)

**Comment by leonsoft-kras** [comment] 2017-10-03 09:48
version ?

**Comment by leonsoft-kras** [comment] 2017-10-03 09:54
You see how difficult it is to understand each other if you write 2 words.
What version of TR GUI?

**Comment by leonsoft-kras** [comment] 2017-10-03 09:55
#1011, #1006 ?

**Comment by patrik-b** [comment] 2017-10-03 10:02
I did misunderstand your question. 

For what I know it's the "latest" version. I can't see the version right now. The menu option is not available (it's grey). I get endless of this error dialog boxes.

<img width="498" alt="skarmklipp 2017-10-03 12 00 36" src="https://user-images.githubusercontent.com/32481310/31119825-940d52d4-a832-11e7-9b70-d3a965e5365a.png">
<img width="501" alt="skarmklipp 2017-10-03 12 00 23" src="https://user-images.githubusercontent.com/32481310/31119826-940e8640-a832-11e7-9a92-e6cc9e825468.png">
<img width="497" alt="skarmklipp 2017-10-03 12 00 13" src="https://user-images.githubusercontent.com/32481310/31119827-940ff886-a832-11e7-86eb-0eeddf035da3.png">
<img width="501" alt="skarmklipp 2017-10-03 12 00 04" src="https://user-images.githubusercontent.com/32481310/31119828-9411474a-a832-11e7-9cca-827ba072f369.png">

**Comment by cryptochrome** [comment] 2017-10-03 12:53
@patrik-b I can confirm, I have seen the same errors. You have to upgrade to the latest version of TR. Version 5.10+ works on High Sierra.

**Comment by leonsoft-kras** [comment] 2017-10-03 13:24
We will not close the Issue until all fans of High Sierra will not switch to this clone TRGUI (v.5.10)

**Comment by Yeehaareal** [comment] 2017-10-03 19:00
Unfortunately it is impossible to copy TRGUI to Apps. The operation can’t be completed because one or more required items can’t be found.
(Error code -43)

**Comment by MrXavierLin** [comment] 2017-10-04 06:35
same problem here, just upgraded to high sierra and got the same error message as patrik-b had.

**Comment by cryptochrome** [comment] 2017-10-04 09:28
Do you guys even read? As stated above, this issue has been fixed in the last release 5.10.

**Comment by happyjaxx** [comment] 2017-10-07 19:12
Darn, is doing "brew cask install transmission-remote-gui" that hard ? :-)

**Comment by kevinxw** [comment] 2017-10-07 23:24
Not so hard if this command is put in the README.

**Comment by PeterDaveHello** [comment] 2017-10-08 10:33
I can put it in the readme later, just need to confirm some of the details.

The problem is: many people downloaded the old, deprecated version but report it's not working here the new version 😞

**Comment by kevinxw** [comment] 2017-10-08 20:30
You can just remove the obsolete download from source forge https://sourceforge.net/projects/transgui/
or update it. Then people will stop getting confused. Because the "latest version" they downloaded does have the issue.

**Comment by PeterDaveHello** [comment] 2017-10-08 23:30
@kevinxw I don't have permission on there, @leonsoft-kras do you?

**Comment by leonsoft-kras** [comment] 2017-10-09 00:11
I'm not the author of the project https://sourceforge.net/projects/transgui
This project is my modified version.

The author of the project at sourceforge.net (and earlier on Google) could not be reached.

**Comment by PeterDaveHello** [comment] 2017-10-09 02:35
I added a note about it in the issue template first.

**Comment by leonsoft-kras** [comment] 2017-10-09 03:45
ok, thanks)

**Comment by PeterDaveHello** [comment] 2017-10-09 05:30
I also updated the document about macOS client installation, feedback and pull requests are welcome.

**Comment by jason-akashic** [comment] 2017-10-10 08:01
New version works for a hot minute or two then crashes every time for me.  Happy to help debug.

**Comment by jason-akashic** [comment] 2017-10-11 17:46
After leaving in frozen state for many hours, app has sprung back to life.  Must've been a big database rebuild or whatnot.

**Comment by jason-akashic** [comment] 2017-10-14 18:15
Actually,  sorry, it's still freezing pretty much constantly for me on High Sierra.

**Comment by leonsoft-kras** [comment] 2017-10-15 01:28
Set the speed to 5120 or less. Report the result.
![default](https://user-images.githubusercontent.com/11468577/31580726-bdee5964-b182-11e7-9ca0-30ff9a391a96.png)

**Comment by PeterDaveHello** [comment] 2017-11-14 09:33
Let's close this.

**Closed by PeterDaveHello** 2017-11-14 09:33 UTC
Labels: help wanted

**Comment by lieolon** [comment] 2018-12-08 10:04
Transmission Remote GUI (5.0.1) doesn't work on MAC OS Mojave 10.14.2

**Comment by PeterDaveHello** [comment] 2018-12-08 10:05
@lieolon this is a very old version, please try the newer ones.

**Comment by lieolon** [comment] 2018-12-08 10:45
where to get a newer version, only 5.0.1 downloads
